### ISSUE TITLE
Should commit generated files ?

### ISSUE THREAD

**Issue by prataprc** [ikatyang/tree-sitter-toml#6]
Looks like the committed files `node-types.json`, `parser.c` and `parser.h` are outdated. When I generate the new set of files:

```
-#define LANGUAGE_VERSION 10
+#define LANGUAGE_VERSION 11
```

My problem is I am intending to use this repo as a `submodule` within my repo `github.com/prataprc/ted`. And the differences in generated files, is forcing a deviation from my local clone and the remote.

**Comment by ikatyang** [comment]
Ref: https://github.com/tree-sitter/tree-sitter/issues/240

I'm not sure if I should commit them, but the official tree-sitter grammars did commit them. I guess the problem is that I did not update these generated files that often.

I've just updated them in https://github.com/ikatyang/tree-sitter-toml/commit/ea45e670ee7d0f6a67a07eabf5363b0e96ea8935.

**Comment by prataprc** [comment]
Working with `git submodules` is bit of a pain. On the other hand there is no use in re-inventing tree-sitter grammars for toml. Would be nice if all of us can use the same grammar and make it a golden standard.

For now this fixes the issue, for long term though, please do think about supporting `git submodules`.

Thanks,
